# Generated by Django 4.0.8 on 2023-04-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salt_dev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMergeList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mzone', models.IntegerField(verbose_name='主区')),
                ('cozone', models.CharField(blank=True, max_length=120, verbose_name='副区')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneList',
            fields=[
                ('zone_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ZoneID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('ip', models.CharField(blank=True, max_length=120, verbose_name='IP')),
                ('id', models.CharField(max_length=120, verbose_name='ID')),
                ('db', models.CharField(blank=True, max_length=120, verbose_name='DB_IP')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近一次更新时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('m_zone', models.IntegerField(default=0, verbose_name='主区')),
                ('minion_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salt_dev.minionlist')),
            ],
            options={
                'verbose_name': 'Zone列表',
                'verbose_name_plural': 'Zone列表',
                'ordering': ['zone_id'],
            },
        ),
    ]
