# Generated by Django 4.0.8 on 2023-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMove',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_id', models.IntegerField(verbose_name='ZoneID')),
                ('tg_minion', models.CharField(blank=True, max_length=120, verbose_name='目标主机')),
                ('port', models.CharField(max_length=120, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近一次更新时间')),
            ],
        ),
    ]
