# Generated by Django 4.0.8 on 2023-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConf',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='参数名称')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='参数键')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='参数值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '系统参数表',
                'verbose_name_plural': '系统参数表',
                'ordering': ['name'],
            },
        ),
    ]
