# Generated by Django 4.0.8 on 2023-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinionList',
            fields=[
                ('minion_id', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='MinionID')),
                ('ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='IP地址')),
                ('do_main', models.CharField(blank=True, max_length=200, null=True, verbose_name='域名')),
                ('minion_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Minion版本')),
                ('system_issue', models.CharField(blank=True, max_length=200, null=True, verbose_name='系统版本')),
                ('sn', models.CharField(blank=True, max_length=200, null=True, verbose_name='SN')),
                ('cpu_num', models.IntegerField(blank=True, null=True, verbose_name='CPU核数')),
                ('cpu_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='CPU型号')),
                ('sys', models.CharField(blank=True, max_length=200, null=True, verbose_name='系统类型')),
                ('kernel', models.CharField(blank=True, max_length=200, null=True, verbose_name='内核')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='品牌名称')),
                ('ipv4_address', models.CharField(blank=True, max_length=900, null=True, verbose_name='ipv4地址')),
                ('mac_address', models.CharField(blank=True, max_length=900, null=True, verbose_name='mac地址')),
                ('localhost', models.CharField(blank=True, max_length=200, null=True, verbose_name='主机名')),
                ('mem_total', models.IntegerField(blank=True, null=True, verbose_name='内存大小')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近一次更新时间')),
                ('minion_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Minion状态')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述备注')),
            ],
            options={
                'verbose_name': 'Minion列表',
                'verbose_name_plural': 'Minion列表',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='SaltKeyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_id', models.CharField(max_length=120, verbose_name='MinionID')),
                ('certification_status', models.CharField(max_length=20, verbose_name='认证状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近一次更新时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Salt-key信息表',
                'verbose_name_plural': 'Salt-key信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaltCmdInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_cmd', models.CharField(max_length=100, verbose_name='命令')),
                ('salt_cmd_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('salt_cmd_module', models.CharField(blank=True, max_length=200, null=True, verbose_name='模块')),
                ('salt_cmd_source', models.CharField(blank=True, max_length=200, null=True, verbose_name='命令来源')),
                ('salt_cmd_doc', models.TextField(blank=True, null=True, verbose_name='命令帮助信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近一次更新时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述备注')),
            ],
            options={
                'verbose_name': 'salt命令集表',
                'verbose_name_plural': 'salt命令集表',
                'ordering': ['salt_cmd_type', 'salt_cmd'],
                'unique_together': {('salt_cmd', 'salt_cmd_type')},
            },
        ),
    ]
